const GET_SINGLE_USER = "GET_SINGLE_USER";
const GET_SINGLE_USER_FAILED = "GET_SINGLE_USER_FAILED";
const GET_ALL_USERS = "GET_ALL_USERS";
const GET_ALL_USERS_FAILED = "GET_ALL_USERS_FAILED";
const CREATE_USER = "CREATE_USER";
const CREATE_USER_FAILED = "CREATE_USER_FAILED";
const DELETE_USER = "DELETE_USER";
const DELETE_USER_FAILED = "DELETE_USER_FAILED";
const UPDATE_USER = "UPDATE_USER";
const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";
const GET_USER_LOCATION = "GET_USER_LOCATION";
const GET_USER_LOCATION_FAILED = "GET_USER_LOCATION_FAILED";

export {
  GET_SINGLE_USER,
  GET_SINGLE_USER_FAILED,
  GET_ALL_USERS,
  GET_ALL_USERS_FAILED,
  CREATE_USER,
  CREATE_USER_FAILED,
  DELETE_USER,
  DELETE_USER_FAILED,
  UPDATE_USER,
  UPDATE_USER_FAILED,
  GET_USER_LOCATION,
  GET_USER_LOCATION_FAILED,
};
